'use strict';
const canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d'),$=s=>document.getElementById(s),TAU=Math.PI*2;
let W,H,scale,ox,oy,time=0,last=0,mode='title',attempts=0,player,boss,shots=[],particles=[],hazards=[],keys={},padPrev={},charge=0,charging=false,shake=0,noticeTime=0,phase2=false,audio,muted=false;
const arena={x:500,y:370,r:305}, clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function resize(){W=innerWidth;H=innerHeight;canvas.width=W*devicePixelRatio;canvas.height=H*devicePixelRatio;scale=Math.min(W/1100,H/850);ox=W/2-500*scale;oy=H/2-370*scale;}addEventListener('resize',resize);resize();
function reset(){player={x:500,y:550,hp:100,fp:100,sp:100,flasks:3,angle:-Math.PI/2,roll:0,inv:0,cd:0,heal:0,swing:0,regen:0,dx:0,dy:-1};boss={x:500,y:260,hp:1200,max:1200,angle:Math.PI/2,state:'idle',timer:2,move:0,flash:0,combo:0};shots=[];particles=[];hazards=[];phase2=false;charge=0;charging=false;noticeTime=0;shake=0;}reset();
function sound(freq,duration=.1,type='sine',vol=.04){if(!audio||muted)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.4),audio.currentTime+duration);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function announce(s,t=2){$('notice').textContent=s;noticeTime=t;}
function start(){if(mode==='pause'){mode='play';document.body.classList.add('playing');last=performance.now();return;}try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}reset();attempts++;mode='play';document.body.classList.add('playing');announce('THE LAST WATCH',2.5);}
$('begin').onclick=start;
function pause(){if(mode!=='play'&&mode!=='pause')return;if(mode==='pause'){start();return;}mode='pause';keys={};charging=false;charge=0;document.body.classList.remove('playing');$('eyebrow').textContent='A MOMENT BETWEEN BLOWS';$('title').textContent='PAUSED';$('description').textContent='Take a breath. The sanctum can wait.';$('begin').textContent='RETURN TO THE FIGHT';$('tip').textContent='Esc or the pause button to resume.';}$('pause').onclick=pause;
function end(win){mode=win?'win':'dead';charging=false;setTimeout(()=>{if(mode!=='dead'&&mode!=='win')return;document.body.classList.remove('playing');$('eyebrow').textContent=win?'THE WATCH IS ENDED':'THE SANCTUM REMEMBERS';$('title').textContent=win?'VOW FULFILLED':'YOU DIED';$('description').innerHTML=win?'The hollow crown falls silent.<br>A new dawn belongs to no king.':'Read the wind-up. Dodge through the blow.<br>Even a king must pause to breathe.';$('begin').textContent=win?'FACE HIM AGAIN':'RISE AGAIN';$('tip').textContent=`Attempt ${attempts} · ${win?'The last king has fallen.':Math.round((1-boss.hp/boss.max)*100)+'% of the king’s health taken.'}`;},1000);}
function burst(x,y,color,n=12,speed=100){for(let i=0;i<n;i++){const a=Math.random()*TAU,v=Math.random()*speed;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,t:.3+Math.random()*.5,max:.8,color,r:1+Math.random()*3});}}
function constrain(p){const d=dist(p,arena),r=arena.r-22;if(d>r){p.x=arena.x+(p.x-arena.x)*r/d;p.y=arena.y+(p.y-arena.y)*r/d;}}
function action(k){if(k==='Escape'){pause();return;}if(mode!=='play')return;if(k===' '&&player.sp>=25&&player.roll<=0&&player.cd<.2&&player.heal<=0){player.sp-=25;player.regen=.65;player.roll=.34;player.inv=.34;const m=moveInput();let len=Math.hypot(m.x,m.y);player.dx=len?m.x/len:Math.cos(player.angle);player.dy=len?m.y/len:Math.sin(player.angle);charging=false;charge=0;sound(170,.16,'triangle');}
if(k==='j'&&player.cd<=0&&player.roll<=0&&player.heal<=0&&player.sp>=18){player.sp-=18;player.regen=.65;player.cd=.43;player.swing=.22;player.angle=Math.atan2(boss.y-player.y,boss.x-player.x);if(dist(player,boss)<105)hitBoss(65);sound(280,.12,'sawtooth',.02);}
if(k==='k'&&player.cd<=0&&player.roll<=0&&player.heal<=0&&player.fp>=14){charging=true;charge=0;}
if(k==='e'&&player.flasks>0&&player.hp<100&&player.heal<=0&&player.roll<=0&&player.cd<=0){player.heal=.95;player.cd=1;player.flasks--;charging=false;charge=0;burst(player.x,player.y,'#e8b75d',20,40);sound(500,.4);}}
function cast(){if(!charging)return;charging=false;if(mode!=='play'||player.fp<14)return;const powered=charge>.8&&player.fp>=28;player.fp-=powered?28:14;player.cd=.45;const a=Math.atan2(boss.y-player.y,boss.x-player.x);shots.push({x:player.x,y:player.y,vx:Math.cos(a)*460,vy:Math.sin(a)*460,t:2,powered});charge=0;sound(powered?600:800,.3,'sine',.04);}
addEventListener('keydown',e=>{let k=e.key.length===1?e.key.toLowerCase():e.key;if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(k))e.preventDefault();if(!keys[k])action(k);keys[k]=true;});addEventListener('keyup',e=>{let k=e.key.length===1?e.key.toLowerCase():e.key;keys[k]=false;if(k==='k')cast();});addEventListener('blur',()=>{keys={};if(mode==='play')pause();});
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);const k=b.dataset.key;keys[k]=true;action(k);};b.onpointerup=b.onpointercancel=e=>{keys[b.dataset.key]=false;if(b.dataset.key==='k')cast();};});
let stick={x:0,y:0};function gamepad(){const p=navigator.getGamepads?.();const g=p&&Array.from(p).find(Boolean);stick={x:0,y:0};if(!g)return;stick.x=Math.abs(g.axes[0])>.18?g.axes[0]:0;stick.y=Math.abs(g.axes[1])>.18?g.axes[1]:0;const map={1:' ',2:'e',5:'j',7:'k',9:'Escape'};for(const [i,k]of Object.entries(map)){const down=g.buttons[i]?.pressed;if(down&&!padPrev[i]){if(i==='9'&&(mode==='title'||mode==='dead'||mode==='win'))start();else action(k);}if(!down&&padPrev[i]&&k==='k')cast();padPrev[i]=down;}}
function moveInput(){return{x:(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0)+stick.x,y:(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0)+stick.y};}
function hitBoss(d){if(boss.hp<=0)return;boss.hp=Math.max(0,boss.hp-d);boss.flash=.12;burst(boss.x,boss.y,'#d6b378',18);shake=4;sound(90,.16,'triangle',.08);if(boss.hp<=0)end(true);}
function hurt(d){if(player.inv>0||mode!=='play')return;player.hp=Math.max(0,player.hp-d);player.inv=.65;shake=9;burst(player.x,player.y,'#b44e3e',20,160);sound(65,.25,'sawtooth',.04);if(player.hp<=0)end(false);}
function bossAttack(){boss.state='windup';boss.move=(boss.combo++)%3;boss.timer=boss.move===0?.85:boss.move===1?1.05:1.2;if(phase2)boss.timer*=.8;boss.angle=Math.atan2(player.y-boss.y,player.x-boss.x);boss.tx=player.x;boss.ty=player.y;}
function update(dt){gamepad();time+=dt;particles=particles.filter(p=>{p.t-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;return p.t>0;});shake=Math.max(0,shake-35*dt);if(mode!=='play')return;
noticeTime-=dt;if(noticeTime<=0)$('notice').textContent='';player.inv-=dt;player.cd-=dt;player.swing-=dt;player.regen-=dt;boss.flash-=dt;if(player.regen<=0&&player.roll<=0&&!charging)player.sp=Math.min(100,player.sp+30*dt);player.fp=Math.min(100,player.fp+3*dt);
if(player.heal>0){player.heal-=dt;if(player.heal<=0){player.hp=Math.min(100,player.hp+58);burst(player.x,player.y,'#f3d484',30,70);sound(750,.3);}}
if(charging){charge=Math.min(1.4,charge+dt);if(Math.random()<.5)burst(player.x,player.y,'#83cdd5',1,25);}
const m=moveInput(),len=Math.hypot(m.x,m.y);if(player.roll>0){player.roll-=dt;player.x+=player.dx*420*dt;player.y+=player.dy*420*dt;burst(player.x,player.y,'#8a9d92',1,20);}else if(len){const speed=player.heal>0?65:charging?95:175;player.x+=m.x/Math.max(1,len)*speed*dt;player.y+=m.y/Math.max(1,len)*speed*dt;player.angle=Math.atan2(m.y,m.x);}constrain(player);
if(boss.hp<boss.max*.5&&!phase2){phase2=true;boss.state='recover';boss.timer=1.8;announce('THE CROWN REMEMBERS',3);burst(boss.x,boss.y,'#f4a45c',70,160);hazards.push({x:boss.x,y:boss.y,r:0,max:370,t:2.7,kind:'ring'});sound(55,1,'sawtooth',.04);}
boss.timer-=dt;if(boss.state==='idle'){let d=dist(player,boss);boss.angle=Math.atan2(player.y-boss.y,player.x-boss.x);if(d>88){boss.x+=Math.cos(boss.angle)*(phase2?88:65)*dt;boss.y+=Math.sin(boss.angle)*(phase2?88:65)*dt;}if(boss.timer<=0)bossAttack();}
else if(boss.state==='windup'&&boss.timer<=0){boss.state='attack';boss.timer=boss.move===1?.38:.28;sound(100,.25,'sawtooth',.03);if(boss.move===0){if(dist(player,boss)<135)hurt(26);burst(boss.x,boss.y,'#c9ad79',20,130);}if(boss.move===2){hazards.push({x:boss.tx,y:boss.ty,r:100,t:.3,kind:'blast'});if(Math.hypot(player.x-boss.tx,player.y-boss.ty)<100)hurt(32);if(phase2)hazards.push({x:boss.x,y:boss.y,r:0,max:320,t:2.3,kind:'ring'});shake=7;}}
else if(boss.state==='attack'){if(boss.move===1){boss.x+=Math.cos(boss.angle)*560*dt;boss.y+=Math.sin(boss.angle)*560*dt;if(dist(player,boss)<58)hurt(30);burst(boss.x,boss.y,'#b19563',2,60);}if(boss.timer<=0){boss.state='recover';boss.timer=phase2?.85:1.2;}}
else if(boss.state==='recover'&&boss.timer<=0){boss.state='idle';boss.timer=phase2?.6:.9;}constrain(boss);
shots=shots.filter(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.t-=dt;burst(s.x,s.y,'#a8e6e4',1,20);if(dist(s,boss)<38){hitBoss(s.powered?150:65);return false;}return s.t>0;});
hazards=hazards.filter(h=>{h.t-=dt;if(h.kind==='ring'){h.r+=155*dt;if(Math.abs(dist(player,h)-h.r)<13)hurt(24);}return h.t>0;});
$('hp').style.width=player.hp+'%';$('fp').style.width=player.fp+'%';$('sp').style.width=player.sp+'%';$('flasks').textContent=player.flasks;$('bossHp').style.width=boss.hp/boss.max*100+'%';$('phase').textContent=phase2?'II · THE CROWN REMEMBERS':'I · THE LAST WATCH';$('state').textContent=player.heal>0?'DRINKING…':charging?(charge>.8?'SORCERY CHARGED':'GATHERING LIGHT'):player.sp<25?'STAMINA LOW':'UNBROKEN';}
function circle(x,y,r,fill,stroke,lw=1){ctx.beginPath();ctx.arc(x,y,r,0,TAU);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke();}}
function line(x,y,x2,y2,c,w=1){ctx.strokeStyle=c;ctx.lineWidth=w;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();}
function knight(p,isBoss){const r=isBoss?25:13;ctx.save();ctx.translate(p.x,p.y);circle(2,12,r*1.1,'#0007');ctx.rotate(p.angle+Math.PI/2);if(!isBoss&&p.inv>0&&p.roll<=0)ctx.globalAlpha=.5+Math.sin(time*50)*.25;
ctx.fillStyle=isBoss?(phase2?'#743b2c':'#514b3d'):'#4d6865';ctx.beginPath();ctx.moveTo(-r*.8,0);ctx.lineTo(-r*1.1,r*1.65);ctx.quadraticCurveTo(0,r*1.2,r*1.1,r*1.65);ctx.lineTo(r*.8,0);ctx.fill();
ctx.fillStyle=isBoss?(p.flash>0?'#e6cfaa':'#8b8876'):'#a6b7ae';ctx.strokeStyle='#303c36';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-r,-r*.1);ctx.lineTo(-r*.6,-r*.8);ctx.lineTo(r*.6,-r*.8);ctx.lineTo(r,-r*.1);ctx.lineTo(r*.6,r*.7);ctx.lineTo(-r*.6,r*.7);ctx.closePath();ctx.fill();ctx.stroke();circle(0,-r*.5,r*.43,isBoss?'#45463e':'#586b64','#c1bda0',1);line(-r*.25,-r*.5,r*.25,-r*.5,isBoss?'#efa96b':'#dfe2c4',2);
if(isBoss){ctx.strokeStyle='#c2a768';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-13,-19);ctx.lineTo(-15,-30);ctx.lineTo(-7,-25);ctx.lineTo(0,-35);ctx.lineTo(7,-25);ctx.lineTo(15,-30);ctx.lineTo(13,-19);ctx.stroke();}
ctx.save();ctx.translate(r*.9,0);let a=isBoss?(p.state==='windup'?-.9:p.state==='attack'?1.4:.2):p.swing>0?1.5-p.swing*10:.2;ctx.rotate(a);line(0,10,0,isBoss?-64:-34,isBoss?'#c2b99b':'#d7e0ca',isBoss?7:3);line(-8,0,8,0,'#ac9461',3);ctx.restore();
if(!isBoss&&player.swing>0){ctx.beginPath();ctx.arc(0,0,75,-2.5,.1);ctx.strokeStyle='#e8dfb8aa';ctx.lineWidth=9;ctx.stroke();}ctx.restore();}
function render(){ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.fillStyle='#0a100f';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(ox+(Math.random()-.5)*shake,oy+(Math.random()-.5)*shake);ctx.scale(scale,scale);
const fog=ctx.createRadialGradient(500,300,80,500,370,580);fog.addColorStop(0,'#35433a');fog.addColorStop(.6,'#1b2823');fog.addColorStop(1,'#09100f');ctx.fillStyle=fog;ctx.fillRect(-1000,-1000,3000,3000);
// Arena masonry is drawn in world coordinates, beneath the combat simulation.
circle(500,370,327,'#151e1a','#445045',2);circle(500,370,307,'#303a31','#6e7561',3);ctx.save();ctx.beginPath();ctx.arc(500,370,303,0,TAU);ctx.clip();
for(let row=-1;row<19;row++)for(let col=-1;col<21;col++){const x=col*58+(row%2)*29,y=row*44;const n=Math.sin(row*31+col*73)*.5+.5;ctx.fillStyle=`rgb(${38+n*12},${48+n*12},${40+n*10})`;ctx.fillRect(x+1,y+1,55,41);if(n>.8)line(x+5,y+8,x+23,y+25,'#65705b25');}
for(let r of [80,86,177,182,279,288])circle(500,370,r,null,'#93947530',1);for(let i=0;i<16;i++){let a=i*TAU/16;line(500+Math.cos(a)*184,370+Math.sin(a)*184,500+Math.cos(a)*279,370+Math.sin(a)*279,'#8a91782a');}circle(500,370,37,null,'#a69d7155');for(let i=0;i<8;i++){let a=i*TAU/8;line(500+Math.cos(a)*37,370+Math.sin(a)*37,500+Math.cos(a+Math.PI)*37,370+Math.sin(a+Math.PI)*37,'#a69d7133');}ctx.restore();
for(let i=0;i<12;i++){let a=i*TAU/12,x=500+Math.cos(a)*323,y=370+Math.sin(a)*323;circle(x+4,y+8,18,'#050c0988');ctx.fillStyle='#3a463b';ctx.fillRect(x-13,y-15,26,28);ctx.strokeStyle='#6b7560';ctx.strokeRect(x-13,y-15,26,28);if(i%2===0){let g=ctx.createRadialGradient(x,y,0,x,y,60);g.addColorStop(0,'#d6a65544');g.addColorStop(1,'#d6a65500');ctx.fillStyle=g;ctx.fillRect(x-60,y-60,120,120);circle(x,y,4+Math.sin(time*6+i),'#e6c278');}}
// Fog gate at the southern edge.
for(let i=0;i<18;i++){ctx.globalAlpha=.035;ctx.fillStyle='#d8e0bb';ctx.fillRect(452+i*5,640+Math.sin(time+i)*7,4,52);}ctx.globalAlpha=1;
if(boss.state==='windup'&&mode==='play'){const alpha=.12+Math.sin(time*15)*.05;if(boss.move===0){circle(boss.x,boss.y,135,`rgba(206,123,66,${alpha})`,'#d09b6699',2);}else if(boss.move===1){ctx.save();ctx.translate(boss.x,boss.y);ctx.rotate(boss.angle);ctx.fillStyle=`rgba(224,158,86,${alpha})`;ctx.fillRect(0,-28,270,56);ctx.strokeStyle='#d7a06588';ctx.strokeRect(0,-28,270,56);ctx.restore();}else{circle(boss.tx,boss.ty,100,`rgba(218,145,70,${alpha})`,'#d7b374aa',2);circle(boss.tx,boss.ty,100*(1-clamp(boss.timer/1.2,0,1)),null,'#d7b37477',2);}}
for(const h of hazards){if(h.kind==='ring'){circle(h.x,h.y,h.r,null,'#f2b06ca0',8);circle(h.x,h.y,h.r+6,null,'#f8d19755',2);}else circle(h.x,h.y,h.r,'#eac78a55','#f6d8a6',3);}
if(player.y<boss.y){knight(player,false);knight(boss,true);}else{knight(boss,true);knight(player,false);}if(charging){circle(player.x,player.y,22+charge*8,null,'#a4e1dfaa',2);}
for(const s of shots){ctx.shadowColor='#9be9f2';ctx.shadowBlur=20;circle(s.x,s.y,s.powered?9:5,'#d6ffff');ctx.shadowBlur=0;}for(const p of particles){ctx.globalAlpha=Math.max(0,p.t/p.max);circle(p.x,p.y,p.r,p.color);}ctx.globalAlpha=1;
for(let i=0;i<45;i++){const x=(i*137.2+Math.sin(time*.3+i)*15)%1100,y=(i*73-time*(4+i%4)+85000)%850;circle(x,y,1,'#c7cba133');}ctx.restore();
const vignette=ctx.createRadialGradient(W/2,H/2,H*.2,W/2,H/2,Math.max(W,H)*.7);vignette.addColorStop(0,'#0000');vignette.addColorStop(1,'#020806cc');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);if(mode==='dead'){ctx.fillStyle='#641d1822';ctx.fillRect(0,0,W,H);}}
function frame(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;if(mode!=='pause')update(dt);else gamepad();render();requestAnimationFrame(frame);}requestAnimationFrame(frame);
